name: CI

on:
  workflow_call:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: |
          tflint --init
          tflint

  policy:
    name: Policy

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          download_external_modules: false
          framework: terraform
          output_file_path: console,results.sarif
          output_format: cli,sarif
          skip_check: CKV_TF_1
          skip_path: "examples/"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        # Results are generated only on a success or failure this is required since GitHub by
        # default won't run the next step when the previous one has failed. Security checks that
        # do not pass will 'fail'.
        #
        # We only upload SARIF files when running this step against one of our open-source MCAF
        # modules.
        if: (success() || failure()) && contains(github.repository, 'mcaf')
        with:
          sarif_file: results.sarif

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Run terraform tests
        if: ${{ hashFiles('test/**') != '' }}
        run: terraform test
