name: CI

on:
  workflow_call:
    inputs:
      token:
        description: 'Token to use instead of GITHUB_TOKEN'
        required: false
        type: string

jobs:
  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c #v1.4.1
        with:
          args: --sort-by required
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow

      - name: Commit changes via API
        run: |
          echo "Committing changes..."
          FILES_CHANGED=$(git status --porcelain | awk '{print $2}')
          for file in $FILES_CHANGED; do
            CONTENT=$(base64 -w 0 $file)
            FILENAME=$(basename $file)
            SHA=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/${{ github.repository }}/contents/$file?ref=${{ github.event.pull_request.head.ref }} | jq -r .sha)
            if [ "$SHA" == "null" ]; then
              SHA=""
            fi
            curl -s -X PUT -H "Authorization: token $TOKEN" \
              -d "{\"message\":\"chore(readme): Update module usage\", \"content\":\"$CONTENT\", \"branch\":\"${{ github.event.pull_request.head.ref }}\", \"sha\":\"$SHA\"}" \
              https://api.github.com/repos/${{ github.repository }}/contents/$file
          done
        env:
          TOKEN: ${{ inputs.token || secrets.GITHUB_TOKEN }}

  # If the recursive flag is set to true, the action will not update the main README.md file.
  # Therefore we need to run the action twice, once for the root module and once for the modules directory
  generate-docs-modules:
    name: Generate module docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Render terraform docs inside the README.md
        uses: terraform-docs/gh-actions@6de6da0cefcc6b4b7a5cbea4d79d97060733093c #v1.4.1
        with:
          args: --sort-by required
          recursive-path: modules
          recursive: "true"
        continue-on-error: true # added this to prevent a PR from a remote fork failing the workflow

      - name: Commit changes via API
        run: |
          echo "Committing changes..."
          FILES_CHANGED=$(git status --porcelain | awk '{print $2}')
          for file in $FILES_CHANGED; do
            CONTENT=$(base64 -w 0 $file)
            FILENAME=$(basename $file)
            SHA=$(curl -s -H "Authorization: token $TOKEN" https://api.github.com/repos/${{ github.repository }}/contents/$file?ref=${{ github.event.pull_request.head.ref }} | jq -r .sha)
            if [ "$SHA" == "null" ]; then
              SHA=""
            fi
            curl -s -X PUT -H "Authorization: token $TOKEN" \
              -d "{\"message\":\"chore(readme): Update module usage\", \"content\":\"$CONTENT\", \"branch\":\"${{ github.event.pull_request.head.ref }}\", \"sha\":\"$SHA\"}" \
              https://api.github.com/repos/${{ github.repository }}/contents/$file
          done
        env:
          TOKEN: ${{ inputs.token || secrets.GITHUB_TOKEN }}

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Check formatting
        run: terraform fmt -check -recursive

      - name: Run TFLint
        uses: terraform-linters/setup-tflint@4cb9feea73331a35b422df102992a03a44a3bb33 #v6.2.1 
        with:
          tflint_version: latest
      - run: |
          tflint --init
          tflint

  policy:
    name: Policy

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@5051a5cfc7e4c71d95199f81ffafbb490c7e6213 #v12.3079.0
        with:
          directory: .
          download_external_modules: false
          framework: terraform
          output_file_path: console,results.sarif
          output_format: cli,sarif
          skip_check: CKV_TF_1
          skip_path: "examples/"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        # Results are generated only on a success or failure this is required since GitHub by
        # default won't run the next step when the previous one has failed. Security checks that
        # do not pass will 'fail'.
        #
        # We only upload SARIF files when running this step against one of our open-source MCAF
        # modules.
        if: (success() || failure()) && contains(github.repository, 'mcaf')
        with:
          sarif_file: results.sarif

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 #v6.0.1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd #v3.1.2

      - name: Init Terraform
        run: terraform init -backend=false

      - name: Run terraform tests
        if: ${{ hashFiles('test/**') != '' }}
        run: terraform test
