name: Commit Checks

on:
  pull_request:
  workflow_call:

permissions:
  contents: read
  pull-requests: write

jobs:
  check-commits:
    name: Conventional Commit Check
    runs-on: ubuntu-latest
    steps:
      - name: Check PR title
        id: semantic
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            refactor
          requireScope: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment if failed
        if: always() && (steps.semantic.outputs.error_message != null)
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semantic-pr
          message: |
            ⚠️ This pull request title does not follow the [Conventional Commits](https://www.conventionalcommits.org/) format.

            Please update the title to follow the format: `<type>[!]: <short description>`

            Examples:

            ```
            feat: add new output for X
            fix: correct typo in Y
            refactor: restructure module Z
            chore: update GitHub actions version
            feat!: remove deprecated variable
            ```

            Use `!` after the type (e.g., `feat!:`) to indicate a **breaking change**. You can also include a `BREAKING CHANGE:` footer in the commit body if more context is needed.

      - name: Remove sticky comment if fixed
        if: ${{ steps.semantic.outputs.error_message == null }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: semantic-pr
          delete: true
